### ISSUE TITLE
As a user, I need a method to introduce my known-hosts into the Jenkins agent DinD

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/jenkins-mesos#30]
When using the Jenkins docker provided with this code, we notice that the git process inside the container does not have a known-hosts file. This prevents the process from successfully cloning a repository via SSH.

**Comment by rji** [comment]
#32 adds support for github.com in the dind-agent image and allows a user to use a space-separated string of hosts that will populate the ssh_known_hosts file on the Jenkins master instance. Otherwise, the expectation is that users will build their own Docker images to use as Jenkins build agents, and would likely want to use `ssh-keyscan` themselves to populate this list, since we wouldn't want to add/maintain SSH keys for private Git servers in this project.

I need to update the documentation to better clarify this limitation / expectation.

**Comment by ssk2** [comment]
It looks like the current documentation and workaround are sufficient: http://mesosphere.github.io/jenkins-mesos/docs/configuration.html
