### ISSUE TITLE
jenkins-dind vfs storage driver very slow

### ISSUE THREAD

**Issue by mikestaub** [mesosphere/jenkins-mesos#55]
I noticed that the docker commands being run on the jenkins slaves were painfully slow. When I changed the storage driver from vfs to overlay it was _much_ faster.

My slaves are running CoreOS 766.5.0 on an m3.large EC2 instance with 32gb of SSD storage.

Is this a known issue with the vfs driver, and are there any cons to using the overlay driver?

**Comment by ssk2** [comment]
Hey @mikestaub, that's interesting! We didn't deliberately choose the vfs driver - so I don't see there being a con to using the overlay driver.

I'll experiment with this during the week to see if I can replicate your findings. If you're able to provide a PR with the change you made to the `jenkins-dind` image, that'd be really helpful.

**Comment by mikestaub** [comment]
I created the PR.

I assumed it was intentional as vfs is being explicitly set in the docker daemon args. You might want to try removing it and see if the daemon is smart enough to use the same storage driver as the host docker engine.

I assume the poor performance was due to that fact that the dind image was using a different driver as the host docker daemon.

**Comment by rji** [comment]
In a nutshellm I actually deliberately chose VFS here. With true Docker-in-Docker (e.g. not bind-mounting the socket from the host), VFS is the absolute safest option for a backend because it doesn't use Docker's copy-on-write system. While this makes it slower than other options, it avoids problems between the parent container's filesystem and the child container's copy-on-write system. For more info, see the "Docker-in-Docker: the ugly" section from Jerome's post: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

Although slower than other systems, this approach should work for all of our users out of the box. As always, you should feel free to (and should!) create custom Jenkins build agent Docker images and substitute them out for our default jenkins-dind image in the Jenkins master's configuration. But otherwise, I think our current configuration should be the default for this project, even if that means we take a performance hit.

**Comment by ssk2** [comment]
Thanks for the explanation @rji! @mikestaub - we'll leave the existing configuration for now and see if we can make it easier/clearer for users on how to modify it.
